#' Points–Ranking Reduced Tables
#'
#' These datasets store the reduced points–ranking tables generated by
#' `build.pts.rk()`. They contain only the information required for:
#'
#' * computing classement ranks from points via `rank.from.points()`, and
#' * exporting JSON files used by the online tool.
#'
#' For full player information (club, province, matches, etc.), use
#' `players_m` or `players_f`, which contain the complete registry snapshots.
#'
#' @details
#' ## Contents
#'
#' * `pts_rk_m` is the points–ranking table for **Messieurs**.
#' * `pts_rk_f` is the points–ranking table for **Dames**.
#'
#' Each dataset is a two‑column data frame with:
#'
#' - `pts`: numeric points used for ranking  
#' - `rk`: integer ranking position (1 = highest ranked active player)  
#'
#' Only **active** players are included (inactive players are excluded
#' upstream using `position_bis`).
#'
#' These datasets are produced automatically by `build.pts.rk()` and
#' exported both as `.json` (for the web app) and `.rda` (for local use).
#'
#' @examples
#' # Messieurs
#' data(pts_rk_m)
#' head(pts_rk_m)
#'
#'  \dontrun{# Dames
#' data(pts_rk_f)
#' head(pts_rk_f)
#' }
#'
#' # Use in rank-from-points computation
#' rank.from.points(1500, pts_rk_m)
#'
#' @name pts_rk_m
#' @aliases pts_rk_f
#' @docType data
NULL
